/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.jwebsocket.android.demo;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int authenticated=0x7f020000;
        public static final int bck_100x200=0x7f020001;
        public static final int broadcast=0x7f020002;
        public static final int connected=0x7f020003;
        public static final int disconnected=0x7f020004;
        public static final int mni_cancel=0x7f020005;
        public static final int mni_clear=0x7f020006;
        public static final int mni_connect=0x7f020007;
        public static final int mni_disconnect=0x7f020008;
        public static final int mni_exit=0x7f020009;
        public static final int mni_save=0x7f02000a;
        public static final int send=0x7f02000b;
    }
    public static final class id {
        public static final int btnCancel=0x7f06001e;
        public static final int btnFundBroadcast=0x7f060014;
        public static final int btnFundClearLog=0x7f060015;
        public static final int btnFundSend=0x7f060013;
        public static final int btnSave=0x7f06001f;
        public static final int cameraImgStatus=0x7f060001;
        public static final int cameraLyt=0x7f060000;
        public static final int cfgBtnCancel=0x7f06000a;
        public static final int cfgBtnSave=0x7f06000b;
        public static final int cfgLblPassword=0x7f060008;
        public static final int cfgLblURL=0x7f060004;
        public static final int cfgLblUsername=0x7f060006;
        public static final int cfgLytConfig=0x7f060003;
        public static final int cfgTxfPassword=0x7f060009;
        public static final int cfgTxfURL=0x7f060005;
        public static final int cfgTxfUsername=0x7f060007;
        public static final int classLabel=0x7f060021;
        public static final int classTxt=0x7f060023;
        public static final int fundImgStatus=0x7f06000f;
        public static final int fundLblLogTitle=0x7f060016;
        public static final int invokeBtn=0x7f06002b;
        public static final int keywordsTxt=0x7f06002f;
        public static final int lblFundLog=0x7f060017;
        public static final int lblFundMessage=0x7f06000e;
        public static final int lblFundTarget=0x7f060011;
        public static final int lblUsername=0x7f06001b;
        public static final int lytFund=0x7f06000c;
        public static final int lytFundTitle=0x7f06000d;
        public static final int methodLabel=0x7f060024;
        public static final int methodTxt=0x7f060025;
        public static final int mniCanvasClear=0x7f060034;
        public static final int mniCanvasConnect=0x7f060031;
        public static final int mniCanvasDisconnect=0x7f060032;
        public static final int mniCanvasExit=0x7f060033;
        public static final int parameterLabel=0x7f060029;
        public static final int parameterTxt=0x7f06002a;
        public static final int resultLabel=0x7f06002c;
        public static final int resultTxt=0x7f06002d;
        public static final int rpcLayout=0x7f060020;
        public static final int rpcMenuExit=0x7f060035;
        public static final int rrpcCheckBox=0x7f060026;
        public static final int setButton=0x7f060030;
        public static final int sfvCamera=0x7f060002;
        public static final int statusImage=0x7f060022;
        public static final int targetLabel=0x7f060027;
        public static final int targetTxt=0x7f060028;
        public static final int tweetTxt=0x7f06002e;
        public static final int twitterStreamSettings=0x7f060036;
        public static final int txfFundMessage=0x7f060010;
        public static final int txfFundTarget=0x7f060012;
        public static final int txfPassword=0x7f06001d;
        public static final int txfURL=0x7f06001a;
        public static final int txfUsername=0x7f06001c;
        public static final int txvURL=0x7f060019;
        public static final int widget47=0x7f060018;
    }
    public static final class layout {
        public static final int camera_hvga_p=0x7f030000;
        public static final int config_hvga_p=0x7f030001;
        public static final int fundamentals_hvga_p=0x7f030002;
        public static final int list_item=0x7f030003;
        public static final int main_hvga=0x7f030004;
        public static final int rpc_demo=0x7f030005;
        public static final int tweet_row=0x7f030006;
        public static final int twitter_stream_activity=0x7f030007;
        public static final int twitter_stream_settings=0x7f030008;
    }
    public static final class menu {
        public static final int canvas_menu=0x7f050000;
        public static final int rpc_demo_menu=0x7f050001;
        public static final int twitter_stream_menu=0x7f050002;
    }
    public static final class string {
        public static final int app_name=0x7f040005;
        public static final int mniCanvasClear=0x7f040003;
        public static final int mniCanvasConnect=0x7f040000;
        public static final int mniCanvasDisconnect=0x7f040001;
        public static final int mniCanvasExit=0x7f040002;
        public static final int required_hint=0x7f040004;
    }
}
